### ISSUE TITLE
Investigate human-readable serialization for SymPy expressions

### ISSUE THREAD

**Issue by redeboer** [ComPWA/polarimetry#20]
Goals:
- Dump expressions to some string format that is human-readable (as opposed to [`pickle`](https://docs.python.org/3/library/pickle.html))
- Parse the dumped expressions in such a way that the imported object is equal (same hash) as the object that was dumped)
- (?) Parse into a different version of SymPy, Python and other dependencies (this does not work with `pickle`)

**Comment by mmikhasenko** [comment]
String serialization with `srepr` actually works ok. It is different to print_to_string that I tried before.

The time of the serialization is also ok. With an example I just tried, it started exciting 0.5s at the length of the string `~100_000`

<img width="709" alt="image" src="https://github.com/ComPWA/polarimetry/assets/22725744/7b79c4b8-7dbb-4620-84f5-27fba78ee089">

**Comment by mmikhasenko** [comment]
great note.
I was wondering if there is a way to serialize not-fully-done expressions, e.g. keeping lineshape, momenta folded.
Might be possible it seems

**Comment by mmikhasenko** [comment]
Nonetheless, the `srepr` might be solving the issue.

Of course, it is not ideal, JSON would be better, but surprisingly I could not find the tree-like serialization format.

Could you please check if the entire Lc2pKpi model can be saved as a string?
How long is the string?
What is the time to write and read?
