### ISSUE TITLE
Extend PyPI package code example

### ISSUE THREAD

**Issue by redeboer** [ComPWA/polarimetry#336]
It would be nice to extend the [basic usage example](https://compwa.github.io/polarimetry) of the [`polarimetry-lc2pkpi`](https://pypi.org/project/polarimetry-lc2pkpi) package so that it becomes clearer to the user how to:

- Get the intensity expression and (optionally) replace its symbols by parameter values
- Convert the expression to a numerical function
- Evaluate it over a data sample (i.e., what is the expected input and how to compute the kinematic variables from input Mandelstam variables)

@mmikhasenko any other requirements?

**Comment by mmikhasenko** [comment]
Thanks @redeboer. Here is what I'm thinking of

Let's say we have a tree with two branches, msq_piK and `msq_Kp `.
The example should evaluate the unpolarized intensity on this kinematic point.

The test file `test_tree.root` produced as follows:

```c++
TTree *t = new TTree("Lc2ppiK", "Lc2ppiK");

double msq_piK = 0.64;
double msq_Kp = 4.03;

t->Branch("msq_piK", &msq_piK);
t->Branch("msq_Kp", &msq_Kp);
t->Fill();

msq_piK = 0.68;
msq_Kp = 4.01;
t->Fill();

t->SaveAs("test_tree.root");
```

**Comment by mmikhasenko** [comment]
[test_tree.zip](https://github.com/ComPWA/polarimetry/files/14011029/test_tree.zip)

**Comment by mmikhasenko** [comment]
That is how to do it in julia
```julia
using Lc2ppiKSemileptonicModelLHCb
using Lc2ppiKSemileptonicModelLHCb.ThreeBodyDecay

# get model
model = published_model("Default amplitude model")

# get data
t = LazyTree("C:/Users/Mikhasenko/Downloads/test_tree.root", "Lc2ppiK")

# event loop
weights = map(zip(t.msq_Kp, t.msq_piK)) do (msq_Kp, msq_piK)
    σs = Invariants(ms; σ1=msq_Kpi, σ2=msq_Kp)
    unpolarizedintensity(model, σs)
end 
```

**Comment by mmikhasenko** [comment]
Checked again that Julia code works with `Lc2ppiKSemileptonicModelLHCb` with v0.4.0

**Comment by mmikhasenko** [comment]
I was thinking of the numeric transformation, would not it faster, at least for the one-time evaluation?

**Comment by mmikhasenko** [comment]
Nice, I haven't appreciated the `SympyDataTransformer` before. It's cool stuff.

`sp.symbols("m:4 sigma1:4", nonnegative=True)` not ideal since reintroduce variables, the constraint `nonnegative` is not evident. Would be nice to have it as the model property
```
m0, m1, m2, m3 = model.masses()
σ1, σ2, σ3 = model.invariants()
```

**Comment by mmikhasenko** [comment]
Ok, I think it remain kind-of manual, since there are three cases,
sigma1+sigma2 to sigma3
sigma2+sigma3 to sigma1
sigma3+sigma1 to sigma2

**Comment by mmikhasenko** [comment]
How does the workflow look like, then?
